---
framework: mocha
parallelism: 3
postMerge:
  pattern: 
    - "./test/**/*.spec.ts"
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
     command:
        - npm ci
postRun:
     command:
        - node --version
version: 2.8
