framework: mocha
parallelism: 2

postMerge:
  pattern: 
    - "./test/**/palash.spec.ts"
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
     command:
        - npm ci
postRun:
     command:
        - node --version
version: 1.2
