---
framework: mocha
tier: xsmall
postMerge:
  pattern: 
    - "./test/**/*.spec.ts"
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
     command:
        - yarn bootstrap
        - yarn build:mocha
postRun:
     command:
        - node --version
version: 2.7
